name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu-22:
    # Use GitHub-hosted Ubuntu 22.04 runner
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Build and install dependencies
        # Build and install all dependencies to DDK installation directory.
        run: |
          cd ${{github.workspace}}
          cd thirdparty
          bash build_and_install_dependencies.sh ~/ddk_install $(nproc)

      - name: Build and install library
        # Configure CMake, then build and install the flexiv_ddk INTERFACE library to DDK installation directory.
        run: |
          cd ${{github.workspace}}
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
          make install

      - name: Build examples
        # Find and link to the flexiv_ddk INTERFACE library, then build all examples.
        run: |
          cd ${{github.workspace}}/example
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
          make -j$(nproc)

  # build-macos-12:
  #   # Use self-hosted macOS 12 runner with arm64 processor
  #   runs-on: [self-hosted, macos-12, ARM64]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build and install dependencies
  #       # Build and install all dependencies to DDK installation directory.
  #       run: |
  #         cd ${{github.workspace}}
  #         cd thirdparty
  #         bash build_and_install_dependencies.sh ~/ddk_install $(sysctl -n hw.ncpu)

  #     - name: Build and install library
  #       # Configure CMake, then build and install the flexiv_ddk INTERFACE library to DDK installation directory.
  #       run: |
  #         cd ${{github.workspace}}
  #         mkdir -p build && cd build
  #         cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
  #         make install

  #     - name: Build examples
  #       # Find and link to the flexiv_ddk INTERFACE library, then build all examples.
  #       run: |
  #         cd ${{github.workspace}}/example
  #         mkdir -p build && cd build
  #         cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
  #         make -j$(sysctl -n hw.ncpu)

  #     - name: Build tests
  #       # Find and link to the flexiv_ddk INTERFACE library, then build all tests.
  #       run: |
  #         cd ${{github.workspace}}/test
  #         mkdir -p build && cd build
  #         cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
  #         make -j$(sysctl -n hw.ncpu)

  build-windows-2022:
    # Use GitHub-hosted Windows 2022 runner
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Build and install dependencies
        # Build and install all dependencies to DDK installation directory.
        run: |
          cd ${{github.workspace}}
          cd thirdparty
          bash build_and_install_dependencies.sh ~/ddk_install $(nproc)

      - name: Build and install library
        # Configure CMake, then build and install the flexiv_ddk INTERFACE library to DDK installation directory.
        run: |
          cd ${{github.workspace}}
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
          cmake --build . --target install --config Release

      - name: Build examples
        # Find and link to the flexiv_ddk INTERFACE library, then build all examples.
        run: |
          cd ${{github.workspace}}/example
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/ddk_install
          cmake --build . --config Release -j $(nproc)
